laika/laika/urls.py
# -*- coding: utf-8 -*-
#coding=utf-8
"""laika URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from projects import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^projects/', include('projects.urls')),
    url(r'^prices/', views.prices, name='prices'),
    url(r'^team/', views.team, name='team'),
    url(r'^contacts/$', views.ContactsView, name="contacts"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

laika/projects/urls.py
# -*- coding: utf-8 -*-
#coding=utf-8
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'projects'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^visualization$', views.VisView, {'template_name':'projects/visualization.html'}, name='visview'),
    url(r'^implementation$', views.ImpView, {'template_name':'projects/implementation.html'}, name='impview'),
    url(r'^sketch$', views.SkView, {'template_name':'projects/sketch.html'}, name='skview'),
    url(r'^sketch/(?P<sketch_slug>[-\w]+)/$', views.show_sketch, {'template_name':'projects/project.html'}, name='show_sketch'),
    url(r'^implementation/(?P<implementation_slug>[-\w]+)/$', views.show_implementation, {'template_name':'projects/project.html'}, name='show_implementation'),
    url(r'^visualization/(?P<visualization_slug>[-\w]+)/$', views.show_visualization, {'template_name':'projects/project.html'}, name='show_visualization'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

laika/projects/models.py
# -*- coding: utf-8 -*-
#coding=utf-8
from django.db import models
import uuid
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver

def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return 'static/img/%s/%s/%s' % (filename[:1], filename[2:3], filename)



class Project(models.Model):
    project_name = models.CharField(max_length=255, unique=True, primary_key=True, help_text='Уникальное(для раздела эскизы) значение имени проекта.</br>Unique(in sketch section) project\'s name value.')
    is_Active = models.BooleanField(default=True, help_text='Флаг показа.</br>Displaying flag.')
    description = models.TextField(help_text='Описание проекта.</br>Description of the project.')
    short_description = models.TextField(help_text='Короткое описание проекта. Для показа при наведении.</br> Short description of the project shown while hover.')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.project_name    
        
    class Meta:
        db_table = 'projects'
        ordering = ['-updated_at']
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'

        
class Sketch(models.Model):
    project = models.OneToOneField(Project, related_name='sketch', help_text='Выберите проект. Проект должен быть создан заранее.</br>Choose project. Project should exist.')
    sketch_slug = models.SlugField(max_length=255, unique=True, 
        help_text = 'Уникальное значение для Ссылки эскиза, созданное из имени проекта.</br>Unique value for sketch page URL, created from project\'s name.')
    sketchword = models.CharField(max_length=18, default="sketch", help_text='Дополнительное слово для Ссылки.</br>Extra word for sketch_slug.')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    meta_keywords = models.TextField(help_text='Разделённые запятыми слова\фразы для поисковой оптимизации.</br>Comma-delimited set of SEO keywords for meta tag.')
    meta_description = models.TextField(help_text='Описание для поисковой оптимизации.</br>Content for description meta tag.')

    preview = models.ImageField(blank=False, upload_to=get_file_path, 
        help_text='Изображение для показа на главной странице или в списке проектов.</br>Preview for the main page or projects list.')#, default='static/shop/images/previews/default.png', upload_to=get_file_path)
    
    class Meta:
        db_table = 'sketches'
        ordering = ['-updated_at']
        verbose_name = 'Эскиз'
        verbose_name_plural = 'Эскизы'
        
    def __str__(self):
        return self.project.project_name
        
    @models.permalink
    def get_absolute_url(self):
        return ('projects:show_sketch', (), { 'sketch_slug': self.sketch_slug })


@receiver(pre_delete, sender=Sketch)
def Sketch_delete(sender, instance, **kwargs):
    instance.preview.delete(False)
    
    
class SketchImage(models.Model):
    sketch = models.ForeignKey(Sketch, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(blank=True, upload_to=get_file_path)

@receiver(pre_delete, sender=SketchImage)
def SketchImage_delete(sender, instance, **kwargs):
    instance.image.delete(False)
    

class IndexSketchImage(models.Model):
    image = models.ImageField(blank=False, upload_to=get_file_path)

@receiver(pre_delete, sender=IndexSketchImage)
def IndexSketchImage_delete(sender, instance, **kwargs):
    instance.image.delete(False)

    
class Visualization(models.Model):
    project = models.OneToOneField(Project, related_name='visualization', help_text='Выберите проект. Проект должен быть создан заранее.</br>Choose project. Project should exist.')
    visualization_slug = models.SlugField(max_length=255, unique=True, 
        help_text = 'Уникальное значение для Ссылки эскиза, созданное из имени проекта.</br>Unique value for visualization page URL, created from project\'s name.')
    visualizationword = models.CharField(max_length=18, default="visualization", help_text='Дополнительное слово для Ссылки.</br>Extra word for visualization_slug.')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    meta_keywords = models.TextField(help_text='Разделённые запятыми слова\фразы для поисковой оптимизации.</br>Comma-delimited set of SEO keywords for meta tag.')
    meta_description = models.TextField(help_text='Описание для поисковой оптимизации.</br>Content for description meta tag.')

    preview = models.ImageField(blank=False, upload_to=get_file_path, 
        help_text='Изображение для показа на главной странице или в списке проектов.</br>Preview for the main page or projects list.')#, default='static/shop/images/previews/default.png', upload_to=get_file_path)
    
    class Meta:
        db_table = 'visualizations'
        ordering = ['-updated_at']
        verbose_name = 'Визуализация'
        verbose_name_plural = 'Визуализации'
        
    def __str__(self):
        return self.project.project_name
        
    @models.permalink
    def get_absolute_url(self):
        return ('projects:show_visualization', (), { 'visualization_slug': self.visualization_slug })


@receiver(pre_delete, sender=Visualization)
def Visualization_delete(sender, instance, **kwargs):
    instance.preview.delete(False)
    
class VisualizationImage(models.Model):
    visualization = models.ForeignKey(Visualization, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(blank=True, upload_to=get_file_path)

@receiver(pre_delete, sender=VisualizationImage)
def VisualizationImage_delete(sender, instance, **kwargs):
    instance.image.delete(False)

    
class Implementation(models.Model):
    project = models.OneToOneField(Project, related_name='implementation', help_text='Выберите проект. Проект должен быть создан заранее.</br>Choose project. Project should exist.')
    implementation_slug = models.SlugField(max_length=255, unique=True, 
        help_text = 'Уникальное значение для Ссылки эскиза, созданное из имени проекта.</br>Unique value for implementation page URL, created from project\'s name.')
    implementationword = models.CharField(max_length=18, default="implementation", help_text='Дополнительное слово для Ссылки.</br>Extra word for implementation_slug.')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    meta_keywords = models.TextField(help_text='Разделённые запятыми слова\фразы для поисковой оптимизации.</br>Comma-delimited set of SEO keywords for meta tag.')
    meta_description = models.TextField(help_text='Описание для поисковой оптимизации.</br>Content for description meta tag.')

    preview = models.ImageField(blank=False, upload_to=get_file_path, 
        help_text='Изображение для показа на главной странице или в списке проектов.</br>Preview for the main page or projects list.')
        
    
    class Meta:
        db_table = 'implementations'
        ordering = ['-updated_at']
        verbose_name = 'Реализация'
        verbose_name_plural = 'Реализации'
        
    def __str__(self):
        return self.project.project_name
        
    @models.permalink
    def get_absolute_url(self):
        return ('projects:show_implementation', (), { 'implementation_slug': self.implementation_slug })


@receiver(pre_delete, sender=Implementation)
def Implementation_delete(sender, instance, **kwargs):
    instance.preview.delete(False)
    
    
class ImplementationImage(models.Model):
    implementation = models.ForeignKey(Implementation, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(blank=True, upload_to=get_file_path)


@receiver(pre_delete, sender=ImplementationImage)
def ImplementationImage_delete(sender, instance, **kwargs):
    instance.image.delete(False)

laika/projects/views.py
# -*- coding: utf-8 -*-
#coding=utf-8
from django.shortcuts import render, get_object_or_404, render_to_response, redirect
from django.template import RequestContext
import random
from .models import Sketch, Visualization, Implementation, Project, IndexSketchImage
from django.conf import settings
from django.core.mail import send_mail, EmailMultiAlternatives

from django.http import HttpResponse

site_name = settings.SITE_NAME


def index(request, template_name='projects/index.html'):
    if request.method == 'POST':
        postdata = request.POST.copy()
        mess_name = postdata.get('mess_name','')
        mess_email = postdata.get('mess_email','')
        mess_subject = 'Заявка для рассчёта стоимости проекта'
        mess_message = postdata.get('mess_message','')
        mess_phone = postdata.get('mess_phone','')
        mess_object = postdata.get('mess_object','')
        mess_area = postdata.get('mess_area','')
        mess_address = postdata.get('mess_address','')
        mess_from_email, mess_to = 'sender@laikadesign.ru', 'sender@laikadesign.ru'
        mess_text_content = ''
        mess_html_content = '<h3>Имя:</h3><p>' + mess_name +'</p><h3>Почта:</h3><p>'+ mess_email +'</p><h3>Телефон:</h3>\
            <p>' + mess_phone + '</p><h3>Объект:</h3><p>' + mess_object + '</p><h3>Площадь:</h3><p>' + mess_area + '</p><h3>Адрес:</h3>\
            <p>' + mess_address + '</p><br><h3>Сообщение:</h3><p>' + mess_message + '</p>'
        mess_msg = EmailMultiAlternatives(mess_subject, mess_text_content, mess_from_email, [mess_to])
        mess_msg.attach_alternative(mess_html_content, "text/html")
        mess_msg.send()
        return redirect(request.META['HTTP_REFERER'])

    # последние визуализации
    last_five = Project.objects.filter(is_Active=True)[0:5]
    active_projects = Project.objects.filter(is_Active=True)
    active_vis = []
    last_five_vis = []
    for i in active_projects:
        if hasattr(i, 'visualization'):
            active_vis.append(i.visualization)
    last_five_vis = active_vis[0:5]
    firstRand = random.randint(0, len(last_five_vis)-1)
    secondRand = random.randint(0, len(last_five_vis)-1)
    while secondRand == firstRand:
        secondRand = random.randint(0, len(last_five_vis)-1)
        
    #рандомные картинки    
    images = IndexSketchImage.objects.all()
    firstRandomImage = random.randint(0, len(images)-1)
    secondRandomImage = random.randint(0, len(images)-1)
    while secondRandomImage == firstRandomImage:
        secondRandomImage = random.randint(0, len(images)-1)
    context = {
        'site_name':site_name,
        'location':'index',
        'firstRand':last_five_vis[firstRand],
        'secondRand':last_five_vis[secondRand],
        'firstRandomImage':images[firstRandomImage].image,
        'secondRandomImage':images[secondRandomImage].image,
    }
    return render(request, template_name, context)

def prices(request, template_name='projects/prices.html'):
    context = {'site_name':site_name, 'location':'price'}
    return render(request, template_name, context)
    
def show_sketch(request, sketch_slug, template_name='projects/project.html'):
    p = get_object_or_404(Sketch, sketch_slug=sketch_slug)
    page_title = p.project
    meta_keywords = p.meta_keywords
    meta_description = p.meta_description
    back = 'skview'
    context = {'p':p,'page_title':page_title,'meta_keywords':meta_keywords,'meta_description':meta_description, 'site_name':site_name, 'back':back}
    return render(request, template_name, context)

    
def SkView(request, template_name='projects/sketch.html'):
    page_title = 'Эскизы'
    meta_keywords = 'Эскизы проектов'
    meta_description = 'Эскизы проектов Laikadesign'
    context = {'page_title':page_title,'meta_keywords':meta_keywords,'meta_description':meta_description, 'site_name':site_name, 'location':'ske'}
    return render(request, template_name, context)
    

def show_visualization(request, visualization_slug, template_name='projects/project.html'):
    p = get_object_or_404(Visualization, visualization_slug=visualization_slug)
    page_title = p.project
    meta_keywords = p.meta_keywords
    meta_description = p.meta_description
    back = "visview"
    context = {'p':p,'page_title':page_title,'meta_keywords':meta_keywords,'meta_description':meta_description, 'site_name':site_name, 'back':back}
    return render(request, template_name, context)
    
    
def VisView(request, template_name='projects/visualization.html'):
    page_title = 'Визуализации'
    meta_keywords = 'Визуализации проектов'
    meta_description = 'Визуализации проектов Laikadesign'
    context = {'page_title':page_title,'meta_keywords':meta_keywords,'meta_description':meta_description, 'site_name':site_name, 'location':'vis'}
    return render(request, template_name, context)

    
def show_implementation(request, implementation_slug, template_name='projects/project.html'):
    p = get_object_or_404(Implementation, implementation_slug=implementation_slug)
    page_title = p.project
    meta_keywords = p.meta_keywords
    meta_description = p.meta_description
    back = "impview"
    context = {'p':p,'page_title':page_title,'meta_keywords':meta_keywords,'meta_description':meta_description, 'site_name':site_name, 'back':back}
    return render(request, template_name, context)
    
def ImpView(request, template_name='projects/implementation.html'):
    page_title = 'Реализации'
    meta_keywords = 'Реализации проектов'
    meta_description = 'Реализации проектов Laikadesign'
    context = {'page_title':page_title,'meta_keywords':meta_keywords,'meta_description':meta_description, 'site_name':site_name, 'location':'imp'}
    return render(request, template_name, context)
    
    
def team(request, template_name='projects/team.html'):
    context = {'site_name':site_name, 'location':'team'}
    return render(request, template_name, context)

    
def ContactsView(request, template_name="projects/contacts.html"):
    if request.method == 'POST':
        postdata = request.POST.copy()
        mess_name = postdata.get('mess_name','')
        mess_email = postdata.get('mess_email','')
        mess_phone = postdata.get('mess_phone','')
        mess_subject = postdata.get('mess_subject','')
        mess_message = postdata.get('mess_message','')
        mess_from_email, mess_to = 'sender@laikadesign.ru', 'sender@laikadesign.ru'
        mess_text_content = ''
        mess_html_content = '<h3>Имя:</h3><p>' + mess_name +'</p><h3>Почта:</h3><p>'+ mess_email +'</p><h3>Телефон:</h3>\
            <p>' + mess_phone + '</p><br><h3>Сообщение:</h3><p>' + mess_message + '</p>'
        mess_msg = EmailMultiAlternatives(mess_subject, mess_text_content, mess_from_email, [mess_to])
        mess_msg.attach_alternative(mess_html_content, "text/html")
        mess_msg.send()
        return redirect(request.META['HTTP_REFERER'])
    page_title = 'Контакты'
    meta_keywords = 'Контакты, Laikadesign, Адрес Laikadesign, Телефоны Laikadesign, телефон laikadesign'
    meta_description = 'Контакты Laikadesign'
    context = {'page_title':page_title,'meta_keywords':meta_keywords,'meta_description':meta_description, 'site_name':site_name, 'location':'cont'}
    return render(request, template_name, context)

laika/projects/templates/tags/implementation_list.html
{% load thumbnail %}


{% with active_implementations as imp %}
    <div class="list__scroll">

            {% for i in imp %}

                        <a href="{{ i.get_absolute_url }}" class="project_link">
                            <span class="descr"><p class="descr_text">{{ i.project.short_description|ljust:"10"|linebreaksbr }}</p></span>
                            
                            <img class="projects__list__img" src="{{ i.preview.url }}"  alt="превью реализации">
                            
                        </a>

            {% endfor %}

    </div>
{% endwith %}

laika/projects/templates/tags/index_sketch_images.html
{% with firstRandomImage as fr %}
    <img src="{{ fr.url }}" class="last_five_sketches firstRandomImage"  alt="превью одного из последних эскизов"/>
{% endwith %}
{% with secondRandomImage as sec %}
    <img src="{{ sec.url }}" class="last_five_sketches secondRandomImage"  alt="превью одного из последних эскизов"/>
{% endwith %}

laika/projects/templates/tags/last_five_projects.html
{% load thumbnail %}

{% with firstRand as p %}

            <a href="{{ p.get_absolute_url }}" class="last_five_link project_link firstRand" >
                <span class="descr"><p class="descr_text">{{ p.project.short_description|ljust:"10"|linebreaksbr }}</p></span>
                <img src="{{ p.preview.url }}" id="index__last__five"  alt="превью одной из последних визуализаций">
            </a>

{% endwith %}
{% with secondRand as s %}

            <a href="{{ s.get_absolute_url }}" class="last_five_link project_link secondRand" >
                <span class="descr"><p class="descr_text">{{ s.project.short_description|ljust:"10"|linebreaksbr }}</p></span>
                <img src="{{ s.preview.url }}" id="index__last__five"  alt="превью одной из последних визуализаций">
            </a>

{% endwith %}

laika/projects/templates/tags/last_five_sketches.html
{% load thumbnail %}

{% with last_five_sket as p %}

            <a href="{{ p.get_absolute_url }}" class="last_five_link project_link_small">
                <span class="descr descr_small"><p class="descr_text">{{ p.project.short_description|ljust:"10"|linebreaksbr }}</p></span>
                
                    <img src="{{ p.preview.url }}" class="last_five_sketches"  alt="превью одного из последних эскизов">
                
            </a>

{% endwith %}

laika/projects/templates/tags/navigation.html
<h2 class="h2_menu">Меню</h2>

<div id="mini_menu_close" onclick="document.getElementById('nav_wrap_mid').style.display = 'none';document.getElementById('mini_menu_close').style.display = 'none'; document.getElementById('mini_menu_img').style.display = 'inline'; document.getElementById('mini_menu_logo').style.display = 'none'"/>X</div>
<ul id="menu">
    <li class="menu_li" id="mini_menu_logo">
        <a id="mini_logo_up_link" href="{% url 'index' %}">
            <img id="mini_logo_up" src="{{ MEDIA_URL }}static/logo-up-2.png" alt="Главная страница." nopin = "nopin"/>
        </a>
    </li>
    <li class="menu_li"><h3 class="h3_menu"><a {% if location == 'ske' %} class="menu__a__active" {% else %} class="menu__a" {% endif %}    href="{% url 'projects:skview' %}">Эскизы</a></h3></li>
    <li class="menu_li"><h3 class="h3_menu"><a {% if location == 'vis' %} class="menu__a__active" {% else %} class="menu__a" {% endif %}    href="{% url 'projects:visview' %}">Визуализация</a></h3></li>
    <!--li class="menu_li"><h3 class="h3_menu"><a {% if location == 'imp' %} class="menu__a__active" {% else %} class="menu__a" {% endif %}    href="{% url 'projects:impview' %}">Реализация</a></h3></li-->
    <li class="menu_li"><h3 class="h3_menu"><a {% if location == 'price' %} class="menu__a__active" {% else %} class="menu__a" {% endif %}  href="{% url 'prices' %}">Cтоимость</a></h3></li>
    <li class="menu_li"><h3 class="h3_menu"><a {% if location == 'team' %} class="menu__a__active" {% else %} class="menu__a" {% endif %}  href="{% url 'team' %}">Команда</a></h3></li>
    <li class="menu_li"><h3 class="h3_menu"><a {% if location == 'cont' %} class="menu__a__active" {% else %} class="menu__a" {% endif %}   href="{% url 'contacts' %}">Контакты</a></h3></li>
</ul>
<div class="cb"></div>

laika/projects/templates/tags/sketch_list.html
{% load thumbnail %}


{% with active_sketches as sk %}
    <div class="list__scroll">

            {% for s in sk %}
            
                        <a href="{{ s.get_absolute_url }}" class="project_link">
                            <span class="descr"><p class="descr_text">{{ s.project.short_description|ljust:"10"|linebreaksbr }}</p></span>
                            
                            <img class="projects__list__img" src="{{ s.preview.url }}"  alt="превью эскиза">
                        </a>
          
            {% endfor %}

    </div>
{% endwith %}

laika/projects/templates/tags/visualization_list.html
{% load thumbnail %}


{% with active_visualizations as vis %}
    <div class="list__scroll">

            {% for v in vis %}
            
                        <a href="{{ v.get_absolute_url }}" class="project_link">
                            <span class="descr"><p class="descr_text">{{ v.project.short_description|ljust:"10"|linebreaksbr }}</p></span>
                            
                            <img class="projects__list__img" src="{{ v.preview.url }}"  alt="превью визуализации">
                        </a>

            {% endfor %}

    </div>
{% endwith %}